export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-full">
      <body style={{ minHeight: '100vh', height: '100%', margin: 0, padding: 0, display: 'flex', justifyContent: 'center', alignItems: 'center' }}>{children}</body>
    </html>
  )
}
